import assert from 'node:assert/strict';
import { renderToString } from 'react-dom/server';
import { createElement } from 'react';
import { createServer } from 'vite';
const server = await createServer({ server:{ middlewareMode:true },appType:'custom' });
try {
  const { MockBBotClient } = await server.ssrLoadModule('/src/client/mock.ts');
  const { validMinecraftUsername } = await server.ssrLoadModule('/src/client/types.ts');
  const { App } = await server.ssrLoadModule('/src/App.tsx');
  const client = new MockBBotClient();
  let updates=0;const unsubscribe=client.subscribe(()=>updates++);
  client.createBots(20);
  assert.equal(client.getSnapshot().bots.length,20);
  assert.equal(client.getSnapshot().accounts.length,20);
  assert.equal(client.getSnapshot().settings.javaVersion,'1.8.9');
  client.addInstance();
  const instance=client.getSnapshot().instances.at(-1);
  assert.equal(instance.status,'ACTIVE');
  client.setInstanceStatus(instance.id,'SUSPECT');
  assert.equal(client.getSnapshot().instances.at(-1).status,'SUSPECT');
  const bot='bot-06';client.startBot(bot);
  assert.equal(client.getSnapshot().bots.find(b=>b.id===bot).state,'CONNECTING');
  client.setBotState(bot,'IN_PIT_IDLE');
  assert.ok(client.getSnapshot().bots.find(b=>b.id===bot).instanceId);
  client.recoverBot(bot);
  assert.equal(client.getSnapshot().bots.find(b=>b.id===bot).instanceId,undefined);
  client.stopBot(bot);
  assert.equal(client.getSnapshot().bots.find(b=>b.id===bot).state,'DISCONNECTED');
  client.addAccount('UI Example','SESSION');
  assert.equal(client.getSnapshot().accounts.at(-1).label,'UI Example');
  assert.equal(JSON.stringify(client.getSnapshot()).includes('token'),false);
  client.createJob('mega10c');
  const job=client.getSnapshot().jobs[0];
  assert.equal(job.state,'QUEUED');
  client.setJobState(job.id,'ASSIGNED');
  assert.equal(client.getSnapshot().jobs[0].state,'ASSIGNED');
  client.setJobState(job.id,'COMPLETED');
  assert.equal(client.getSnapshot().jobs[0].state,'COMPLETED');
  assert.ok(updates>=9);unsubscribe();
  for(const name of ['A','Player_123','a'.repeat(16)])assert.ok(validMinecraftUsername(name));
  for(const name of ['', 'a'.repeat(17),'/trade Player','a-b','é'])assert.equal(validMinecraftUsername(name),false);
  assert.throws(()=>client.startTrade('bot-01','/trade Player'));
  client.startTrade('bot-01','Player_123');
  const waiting=client.getTradeState('bot-01');assert.equal(waiting.status,'WAITING_FOR_GUI');
  assert.throws(()=>client.startTrade('bot-01','Again'));
  assert.equal(client.getTradeState('bot-02').status,'IDLE');
  await new Promise(resolve=>setTimeout(resolve,900));
  const open=client.getTradeState('bot-01');assert.equal(open.status,'OPEN');
  const w=open.window;assert.equal(w.slots.length,w.slotCount);
  const click={tradeSessionId:open.tradeSessionId,windowId:w.windowId,slot:w.slotCount,revision:open.revision};
  assert.throws(()=>client.clickTradeSlot('bot-01',{...click,slot:999}));
  assert.throws(()=>client.clickTradeSlot('bot-01',{...click,windowId:-1}));
  assert.throws(()=>client.clickTradeSlot('bot-01',{...click,tradeSessionId:'stale'}));
  assert.throws(()=>client.clickTradeSlot('bot-01',{...click,revision:open.revision-1}));
  client.clickTradeSlot('bot-01',click);
  assert.equal(client.getTradeState('bot-01').window.slots[0],null);
  await new Promise(resolve=>setTimeout(resolve,230));
  assert.equal(client.getTradeState('bot-01').window.slots[0].name,'Diamond Sword');
  assert.ok(client.getTradeState('bot-01').revision>open.revision);
  client.cancelTrade('bot-01');assert.equal(client.getTradeState('bot-01').status,'CLOSED');
  client.startTrade('bot-01','Next');client.simulateTradeTimeout('bot-01');
  assert.equal(client.getTradeState('bot-01').error,'Trade GUI timeout');
  await new Promise(resolve=>setTimeout(resolve,900));assert.equal(client.getTradeState('bot-01').status,'TIMEOUT');
  client.startTrade('bot-01','Last');client.stopBot('bot-01');
  assert.equal(client.getTradeState('bot-01').status,'CLOSED');
  client.startTrade('bot-02','Separate');client.setBotState('bot-02','LOBBY');
  assert.equal(client.getTradeState('bot-02').status,'CLOSED');
  assert.equal(client.getTradeState('bot-03').status,'IDLE');
  const html=renderToString(createElement(App));
  assert.ok(html.includes('Command center')&&html.includes('Java 1.8.9'));
  client.reset();assert.equal(client.getSnapshot().bots.length,6);
  console.log('Mock operations, Trade isolation/validation/click/timeout, and server render: OK');
} finally { await server.close(); }
