import { useEffect, useState, useSyncExternalStore } from 'react';
import { Activity, ArrowRight, Bot as BotIcon, Check, ChevronDown, ChevronRight, CircleHelp, Database, LayoutDashboard, Layers3, ListChecks, MoreHorizontal, Play, Plus, Power, Radio, RotateCcw, ScrollText, Search, Settings2, ShieldCheck, Users, X } from 'lucide-react';
import { bbotClient as client } from './client';
import { ServerConnectionPanel } from './ServerConnectionPanel';
import { LiveViewModal } from './LiveViewModal';
import { RemoteAccountsPanel } from './RemoteAccountsPanel';
import { botStates, validMinecraftUsername, type AccountKind, type Bot, type BotState, type InstanceStatus, type JobStatus, type LogEntry, type PartyCommandResult, type Snapshot, type TradeItem, type TradeState } from './client/types';
type Page = 'dashboard'|'bots'|'instances'|'jobs'|'accounts'|'settings'|'logs';
const nav:{id:Page;label:string;icon:typeof LayoutDashboard}[] = [
  {id:'dashboard',label:'Overview',icon:LayoutDashboard},{id:'bots',label:'Bots',icon:BotIcon},
  {id:'instances',label:'Instances',icon:Layers3},{id:'jobs',label:'Jobs',icon:ListChecks},
  {id:'accounts',label:'Accounts',icon:Users},{id:'settings',label:'Settings',icon:Settings2},
  {id:'logs',label:'Logs',icon:ScrollText}
];
const short:Record<BotState,string> = {DISCONNECTED:'Offline',CONNECTING:'Connecting',LOBBY:'Lobby',JOINING_PIT:'Joining Pit',IN_PIT_IDLE:'Idle',PATHFINDING:'Pathfinding',WORKING:'Working',RECOVERING:'Recovering'};
const tone=(s:string)=> ['IN_PIT_IDLE','ACTIVE','READY','COMPLETED'].includes(s)?'good':['PATHFINDING','WORKING','RUNNING','ASSIGNED'].includes(s)?'teal':['SUSPECT','RECOVERING','CONNECTING','JOINING_PIT','QUEUED'].includes(s)?'amber':['FAILED','EXPIRED'].includes(s)?'red':'quiet';
const rel=(time:number)=>{const m=Math.max(0,Math.floor((Date.now()-time)/60000));return m<1?'たった今':m<60?`${m}分前`:m<1440?`${Math.floor(m/60)}時間前`:`${Math.floor(m/1440)}日前`};
function Badge({status,label}:{status:string;label?:string}){return <span className={`badge ${tone(status)}`}><span className="badge-dot" aria-hidden="true" />{label??status}</span>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><Database size={26}/><strong>{title}</strong><p>{detail}</p></div>}
function SectionHead({kicker,title,action}:{kicker?:string;title:string;action?:React.ReactNode}){return <div className="section-head"><div>{kicker&&<span className="eyebrow">{kicker}</span>}<h2>{title}</h2></div>{action}</div>}
function TradePanel({bot,trade,onAction}:{bot:Bot;trade:TradeState;onAction:(task:()=>void)=>void}){
  const [expanded,setExpanded]=useState(false),[partyOpen,setPartyOpen]=useState(false),[partyUsername,setPartyUsername]=useState(''),[notice,setNotice]=useState(''),[noticeError,setNoticeError]=useState(false),[partyPending,setPartyPending]=useState(false);
  const [username,setUsername]=useState(''),[selected,setSelected]=useState<TradeItem|null>(null),[pending,setPending]=useState(false);
  const busy=['REQUESTING','WAITING_FOR_GUI','OPEN'].includes(trade.status),window=trade.window;
  useEffect(()=>setPending(false),[trade.revision]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3700);return()=>clearTimeout(timer)},[notice]);
  const runParty=async(action:()=>PartyCommandResult|Promise<PartyCommandResult>)=>{if(partyPending)return;setPartyPending(true);try{const result=await action();setNotice(result.serverMessage??result.message);setNoticeError(result.status==='REJECTED');if(result.status==='SENT')setPartyOpen(false);}catch(err){setNotice(err instanceof Error?err.message:'操作に失敗しました');setNoticeError(true);}finally{setPartyPending(false)}};
  const grid=(label:string,items:(TradeItem|null)[],offset:number)=>
    <section className="trade-section"><h4>{label}</h4><div className="trade-grid">{items.map((item,index)=><button key={index} className="trade-slot" aria-label={`${label} slot ${index+1}${item?`: ${item.name} x${item.count}`:''}`} disabled={pending||trade.status!=='OPEN'} onClick={()=>{if(item)setSelected(item);if(!item)return;setPending(true);try{client.clickTradeSlot(bot.id,{tradeSessionId:trade.tradeSessionId!,windowId:window!.windowId,slot:offset+index,revision:trade.revision});}catch{setPending(false);}}}>{item&&<><span className="trade-icon">{item.icon??'▣'}</span><span className="trade-item-name">{item.name}</span><small>x{item.count}</small></>}</button>)}</div></section>;
  return <div className="trade-panel"><div className="bot-command-actions"><button className="mini trade-toggle" aria-expanded={expanded} onClick={()=>{setExpanded(!expanded);setPartyOpen(false)}}>Trade</button><button className="mini" aria-expanded={partyOpen} onClick={()=>{setPartyOpen(!partyOpen);setExpanded(false)}}>Party</button><button className="mini" disabled={partyPending} onClick={()=>runParty(()=>client.warpParty(bot.id))}>Warp</button></div>
    {notice&&<p className={noticeError?'trade-error':'trade-notice'} role={noticeError?'alert':'status'}>{notice}</p>}
    {partyOpen&&<div className="trade-content"><strong>Party</strong><label className="field-label" htmlFor={`party-${bot.id}`}>Minecraft ID</label><input id={`party-${bot.id}`} value={partyUsername} maxLength={16} autoComplete="off" spellCheck={false} onChange={e=>setPartyUsername(e.target.value)} placeholder="ExamplePlayer"/>
      {partyUsername&&!validMinecraftUsername(partyUsername)&&<small className="trade-error">1〜16文字の英数字と _ を入力してください</small>}
      <div className="trade-actions"><button className="button accent" disabled={partyPending||!validMinecraftUsername(partyUsername)} onClick={()=>runParty(()=>client.inviteParty(bot.id,partyUsername))}>Send Party</button><button className="button outline" onClick={()=>{setPartyOpen(false);setPartyUsername('')}}>Cancel</button></div></div>}
    {expanded&&<div className="trade-content"><strong>Target Player</strong>
      {!busy&&<><label className="field-label" htmlFor={`trade-${bot.id}`}>Minecraft username</label><input id={`trade-${bot.id}`} value={username} maxLength={16} autoComplete="off" spellCheck={false} onChange={e=>setUsername(e.target.value)} placeholder="PlayerName"/>
        {username&&!validMinecraftUsername(username)&&<small className="trade-error">1〜16文字の英数字と _ を入力してください</small>}
        <div className="trade-actions"><button className="button accent" disabled={!validMinecraftUsername(username)} onClick={()=>onAction(()=>client.startTrade(bot.id,username))}>Send Trade</button><button className="button outline" onClick={()=>{setExpanded(false);setUsername('')}}>Cancel</button></div></>}
      {trade.targetUsername&&trade.status!=='IDLE'&&<p>Trading with: <b>{trade.targetUsername}</b></p>}
      {trade.status==='WAITING_FOR_GUI'&&<p role="status">Waiting for Trade GUI...</p>}
      {trade.status==='TIMEOUT'&&<p role="alert" className="trade-error">Error: Trade GUI timeout</p>}
      {trade.status==='ERROR'&&<p role="alert" className="trade-error">Error: {trade.error??'Trade failed'}</p>}
      {['CLOSED','COMPLETED'].includes(trade.status)&&<p role="status">Trade {trade.status.toLowerCase()}</p>}
      {busy&&<div className="trade-actions"><button className="button outline" onClick={()=>onAction(()=>client.cancelTrade(bot.id))}>Cancel Trade</button>{client.mode==='mock'&&trade.status==='WAITING_FOR_GUI'&&<button className="button outline" onClick={()=>onAction(()=>client.simulateTradeTimeout(bot.id))}>Simulate Timeout</button>}</div>}
      {window&&trade.status==='OPEN'&&<div className="trade-window"><p className="mono">{window.title} · revision {trade.revision}</p>{grid('Trade Window',window.slots,0)}{grid('Inventory',window.inventory,window.slotCount)}{grid('Hotbar',window.hotbar,window.slotCount+27)}{selected&&<div className="trade-item-detail"><b>{selected.name} x{selected.count}</b>{selected.lore?.map((line,i)=><span key={i}>{line}</span>)}{selected.enchantments?.map((line,i)=><span key={i}>{line}</span>)}{selected.durability!==undefined&&<span>Durability: {selected.durability}</span>}{selected.metadata!==undefined&&<span>Metadata: {selected.metadata}</span>}<button onClick={()=>setSelected(null)}>Close</button></div>}</div>}
    </div>}
  </div>;
}
function BotCard({bot,compact,onAction,trade,onLiveView}:{bot:Bot;compact?:boolean;onAction:(task:()=>void|Promise<void>)=>void;trade?:TradeState;onLiveView?:(bot:Bot)=>void}){
  const active=bot.state!=='DISCONNECTED';
  return <article className={`bot-card ${compact?'compact':''}`}>
    <div className="bot-main"><div className={`bot-avatar ${tone(bot.state)}`}><BotIcon size={21} strokeWidth={1.8}/></div>
      <div className="bot-identity"><strong>{bot.name}</strong><span className="mono faint">{bot.id} · {bot.instanceId??'No instance'}</span></div>
      <Badge status={bot.state} label={short[bot.state]}/></div>
    {!compact&&<div className="bot-details"><span>Position <b className="mono">{bot.state!=='DISCONNECTED'?`${bot.x.toFixed(1)} / ${bot.y.toFixed(1)} / ${bot.z.toFixed(1)}`:'—'}</b></span><span>Job <b className="mono">{bot.jobId??'—'}</b></span>{bot.kickReason&&<span>Kick <b>{bot.kickReason}</b></span>}</div>}
    <div className="card-actions">
      {!active?<button className="mini primary-mini" onClick={()=>onAction(()=>client.startBot(bot.id))}><Play size={15}/> Start</button>:<button className="mini" onClick={()=>onAction(()=>client.stopBot(bot.id))}><Power size={15}/> Stop</button>}
      {client.mode==='mock'&&active&&<button className="mini" onClick={()=>onAction(()=>client.recoverBot(bot.id))}><RotateCcw size={15}/> Recover</button>}
      {!compact&&<button className="mini live-view-button" disabled={!active} onClick={()=>onLiveView?.(bot)}><Radio size={15}/> Live View</button>}
      {!compact&&client.mode==='mock'&&<label className="select-wrap"><span className="sr-only">{bot.name} の状態</span><select value={bot.state} onChange={e=>onAction(()=>client.setBotState(bot.id,e.target.value as BotState))} aria-label={`${bot.name} の状態を試す`}>
        {botStates.map(s=><option key={s} value={s}>{s}</option>)}</select><ChevronDown size={13}/></label>}
    </div>
    {!compact&&trade&&client.mode==='mock'&&<TradePanel bot={bot} trade={trade} onAction={onAction}/>}
  </article>
}
function InstanceCard({id,status,count,lastSeen,onAction}:{id:string;status:InstanceStatus;count:number;lastSeen:number;onAction:(task:()=>void)=>void}){
  return <article className="instance-card"><div className="instance-top"><div className="instance-icon"><Layers3 size={19}/></div><Badge status={status}/></div>
    <h3 className="mono">{id}</h3><p className="muted">{count} bots assigned <span className="bullet">·</span> seen {rel(lastSeen)}</p>
    {client.mode==='mock'&&<div className="instance-actions"><button className="text-button" onClick={()=>onAction(()=>client.setInstanceStatus(id,status==='ACTIVE'?'SUSPECT':'ACTIVE'))}>Mark {status==='ACTIVE'?'suspect':'active'} <ArrowRight size={14}/></button></div>}</article>
}
function NavButton({id,label,icon:Icon,page,setPage}:{id:Page;label:string;icon:typeof LayoutDashboard;page:Page;setPage:(v:Page)=>void}){
  return <button type="button" className={`nav-button ${page===id?'selected':''}`} onClick={()=>setPage(id)} aria-current={page===id?'page':undefined}><Icon size={19} strokeWidth={1.9}/><span>{label}</span></button>
}
function App(){
  const snapshot=useSyncExternalStore(client.subscribe,client.getSnapshot,client.getSnapshot);
  const [page,setPage]=useState<Page>('dashboard'),[more,setMore]=useState(false),[toast,setToast]=useState('');
  const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[accountOpen,setAccountOpen]=useState(false);
  const [accountKind,setAccountKind]=useState<AccountKind>('SESSION'),[accountLabel,setAccountLabel]=useState('');
  const [jobInstance,setJobInstance]=useState('mega10c');
  const [liveBotId,setLiveBotId]=useState<string|null>(null);
  useEffect(()=>{if(!more&&!accountOpen)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMore(false);setAccountOpen(false)}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[more,accountOpen]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3700);return()=>clearTimeout(timer)},[toast]);
  const go=(v:Page)=>{setPage(v);setMore(false);setFilter('all');setQuery('');window.scrollTo({top:0,behavior:'smooth'});};
  const perform=(task:()=>void|Promise<void>,success='操作を送信しました')=>{void Promise.resolve().then(task).then(()=>setToast(success)).catch(err=>setToast(err instanceof Error?err.message:'操作に失敗しました'))};
  const active=snapshot.bots.filter(b=>b.state!=='DISCONNECTED').length;
  const live=snapshot.bots.filter(b=>['IN_PIT_IDLE','PATHFINDING','WORKING'].includes(b.state)).length;
  const pending=snapshot.jobs.filter(j=>['QUEUED','ASSIGNED','RUNNING'].includes(j.state)).length;
  const current=nav.find(n=>n.id===page)!;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">B<span>.</span></span><div><strong>BBot</strong><small>CONTROL ROOM</small></div></div>
      <div className="sidebar-label">WORKSPACE</div><nav className="side-nav" aria-label="メインナビゲーション">{nav.map(n=><NavButton key={n.id} {...n} page={page} setPage={go}/>)}</nav>
      <div className="sidebar-bottom"><div className="connector"><span className="signal-ring"><Radio size={16}/></span><div><b>{client.mode==='remote'?'Remote BBot':'Mock environment'}</b><small>{client.mode==='remote'?(snapshot.remoteConnected?'実Botと同期中':'backendとの接続待ち'):'BBot本体には未接続'}</small></div></div><div className="build-meta">BBOT CONSOLE <span>v0.1 · JAVA 1.8.9</span></div></div>
    </aside>
    <div className="mobile-top"><div className="mobile-brand"><span className="brand-mark">B<span>.</span></span><b>BBot</b></div><span className="mobile-mode"><span className="mode-dot"/> {client.mode==='remote'?'REMOTE MODE':'MOCK MODE'}</span></div>
    <main className="content" id="main"><div className="desktop-top"><div className="breadcrumb">WORKSPACE <ChevronRight size={14}/> {current.label.toUpperCase()}</div><div className="top-right"><span className="version-pill">JAVA EDITION <b>1.8.9</b></span><span className="mode-pill"><span className="mode-dot"/> {client.mode==='remote'?'REMOTE MODE':'MOCK MODE'}</span></div></div>
      <div className="page-head"><div><div className="eyebrow">BBOT / {current.label.toUpperCase()}</div><h1>{page==='dashboard'?'Command center':current.label}</h1><p>{({dashboard:client.mode==='remote'?'実Bot backendを操作・監視する管理画面。':'20クライアントまでを見渡す、Mockの管理画面。',bots:'各Botの状態と操作をまとめて確認。',instances:'発見したPit instanceの状態を確認。',jobs:'イベントの割当と進行状況を確認。',accounts:client.mode==='remote'?'Microsoft Accountの追加とBot割当。':'Session Accountの表示と追加を試す。',settings:client.mode==='remote'?'実Minecraft接続先の設定。':'Mock環境の表示設定と動作値。',logs:client.mode==='remote'?'実Botの操作履歴。':'Mock操作の履歴。秘密情報は記録しません。'} as Record<Page,string>)[page]}</p></div>
        {page==='bots'&&client.mode==='mock'&&<button className="button accent" disabled={snapshot.bots.length>=20} onClick={()=>perform(()=>{client.updateSettings({maxBots:20});client.createBots(20)},'20 BotのMock状態を生成しました')}><Plus size={17}/> Generate 20 Bots</button>}
        {page==='instances'&&client.mode==='mock'&&<button className="button accent" onClick={()=>perform(()=>client.addInstance(),'新しいInstanceを観測しました')}><Plus size={17}/> Add instance</button>}
        {page==='accounts'&&client.mode==='mock'&&<button className="button accent" onClick={()=>setAccountOpen(true)}><Plus size={17}/> Add account</button>}
      </div>
      {client.mode==='remote'&&!snapshot.remoteConnected&&<div className="insight" role="status"><Radio size={18}/><p>backendとの接続待ちです。API_ORIGINとWebSocketプロキシを確認してください。</p></div>}
      {client.mode==='remote'&&page==='jobs'&&<div className="insight"><CircleHelp size={18}/><p>この画面の編集はMockモード用です。実Botの操作はBotsページから行ってください。</p></div>}
      {page==='dashboard'&&<Dashboard data={snapshot} active={active} live={live} pending={pending} go={go} perform={perform}/>}
      {page==='bots'&&<section className="view-section"><div className="toolbar"><div className="filter-row" role="group" aria-label="Bot絞り込み">{[['all','All'],['active','Active'],['idle','Idle'],['offline','Offline']].map(([v,l])=><button key={v} className={`filter ${filter===v?'is-active':''}`} onClick={()=>setFilter(v)}>{l}</button>)}</div><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bot / Instance を検索" aria-label="Bot検索"/></div></div>
        <div className="list-label">FLEET <span>{snapshot.bots.length} / {snapshot.settings.maxBots} BOTS</span></div>
        <div className="bot-grid">{snapshot.bots.filter(b=>(filter==='all'||filter==='active'&&b.state!=='DISCONNECTED'||filter==='offline'&&b.state==='DISCONNECTED'||filter==='idle'&&b.state==='IN_PIT_IDLE')&&(b.name.toLowerCase().includes(query.toLowerCase())||b.id.includes(query.toLowerCase())||b.instanceId?.includes(query.toLowerCase()))).map(b=><BotCard key={b.id} bot={b} trade={snapshot.trades[b.id]??client.getTradeState(b.id)} onAction={perform} onLiveView={bot=>setLiveBotId(bot.id)}/>)}</div>
        {!snapshot.bots.some(b=>(filter==='all'||filter==='active'&&b.state!=='DISCONNECTED'||filter==='offline'&&b.state==='DISCONNECTED'||filter==='idle'&&b.state==='IN_PIT_IDLE')&&(b.name.toLowerCase().includes(query.toLowerCase())||b.instanceId?.includes(query.toLowerCase())))&&<Empty title="該当するBotがありません" detail="条件を変更して確認してください。"/>}</section>}
      {page==='instances'&&<section className="view-section"><div className="insight"><Activity size={18}/><p>Instance一覧は固定ではありません。Mockで追加・状態変更を試せます。確認済みの集合であり、総instance数ではありません。</p></div>
        <div className="list-label">OBSERVED INSTANCES <span>{snapshot.instances.length} FOUND</span></div><div className="instance-grid">{snapshot.instances.map(i=><InstanceCard key={i.id} id={i.id} status={i.status} count={snapshot.bots.filter(b=>b.instanceId===i.id).length} lastSeen={i.lastSeen} onAction={perform}/>)}</div></section>}
      {page==='jobs'&&client.mode==='mock'&&<section className="view-section"><div className="job-actions"><label>Mock event for <select value={jobInstance} onChange={e=>setJobInstance(e.target.value)}>{snapshot.instances.map(i=><option key={i.id} value={i.id}>{i.id}</option>)}</select></label><button className="button accent" onClick={()=>perform(()=>client.createJob(jobInstance),'Mock Jobを追加しました')}><Plus size={17}/> Create job</button></div>
        <div className="list-label">JOB QUEUE <span>{snapshot.jobs.length} TOTAL</span></div><div className="job-list">{snapshot.jobs.map(j=><article className="job-card" key={j.id}><div className="job-header"><div className="job-icon"><ListChecks size={18}/></div><div className="job-title"><strong>{j.eventType}</strong><span className="mono faint">{j.id} · {j.instanceId}</span></div><Badge status={j.state}/></div><div className="job-foot"><span className="mono">{j.x} / {j.y} / {j.z}</span><span>{j.botId??'Unassigned'}</span></div><div className="job-state"><span>Mock status</span><label className="select-wrap"><select aria-label={`${j.id} の状態`} value={j.state} onChange={e=>perform(()=>client.setJobState(j.id,e.target.value as JobStatus))}>{(['QUEUED','ASSIGNED','RUNNING','COMPLETED','FAILED','EXPIRED'] as JobStatus[]).map(s=><option key={s}>{s}</option>)}</select><ChevronDown size={13}/></label></div></article>)}</div></section>}
      {page==='accounts'&&client.mode==='remote'&&<RemoteAccountsPanel snapshot={snapshot} notify={setToast}/>}
      {page==='accounts'&&client.mode==='mock'&&<section className="view-section"><div className="insight"><ShieldCheck size={20}/><p>Session AccountはUIのみ。Mockではtokenを入力・保持せず、Bot本体への認証も行いません。</p></div><div className="list-label">ACCOUNTS <span>{snapshot.accounts.length} ADDED</span></div><div className="account-list">{snapshot.accounts.map(a=><div className="account-row" key={a.id}><div className="account-avatar">{a.label.slice(0,1).toUpperCase()}</div><div><strong>{a.label}</strong><span>{a.kind==='SESSION'?'Session Account':'Microsoft Account'} · {a.status==='UNASSIGNED'?'Unassigned':'Mock ready'}</span></div><span className="account-lock"><ShieldCheck size={16}/><span>No token</span></span></div>)}</div></section>}
      {page==='settings'&&client.mode==='remote'&&<section className="view-section settings-grid"><ServerConnectionPanel snapshot={snapshot} notify={setToast}/></section>}
      {page==='settings'&&client.mode==='mock'&&<section className="view-section settings-grid"><ServerConnectionPanel snapshot={snapshot} notify={setToast}/><div className="panel"><div className="panel-icon"><Settings2 size={21}/></div><h2>Mock configuration</h2><p className="muted">この画面だけの一時設定。再読み込みで初期状態に戻ります。</p>
        <SettingSelect label="Bot limit" value={snapshot.settings.maxBots} options={[6,10,15,20]} onChange={value=>perform(()=>client.updateSettings({maxBots:value}))}/>
        <SettingSelect label="Pathfinding concurrency" value={snapshot.settings.pathConcurrency} options={[1,2,3,4]} onChange={value=>perform(()=>client.updateSettings({pathConcurrency:value}))}/>
        <SettingSelect label="Event polling interval" value={snapshot.settings.eventPollingSeconds} options={[5,10,30,60]} suffix="s" onChange={value=>perform(()=>client.updateSettings({eventPollingSeconds:value}))}/>
        <div className="setting-row"><div><strong>Debug mode</strong><small>追加のMock診断表示</small></div><button role="switch" aria-checked={snapshot.settings.debug} aria-label="Debug mode" onClick={()=>perform(()=>client.updateSettings({debug:!snapshot.settings.debug}))} className={`toggle ${snapshot.settings.debug?'on':''}`}><span/></button></div>
      </div><div className="panel"><div className="panel-icon"><CircleHelp size={21}/></div><h2>Environment</h2><div className="about-line"><span>Data source</span><b>MockBBotClient</b></div><div className="about-line"><span>Minecraft</span><b>Java 1.8.9</b></div><div className="about-line"><span>Backend</span><b>Not connected</b></div><p className="muted note">本番用REST / WebSocketクライアントは未接続です。操作はMinecraft Botへ送信されません。</p><button className="button outline full" onClick={()=>{client.reset();setToast('Mock状態を初期化しました')}}><RotateCcw size={16}/> Reset mock data</button></div></section>}
      {page==='logs'&&<section className="view-section"><div className="list-label">ACTIVITY FEED <span>LATEST {snapshot.logs.length}</span></div><div className="log-list">{snapshot.logs.map((l:LogEntry)=><article className="log-row" key={l.id}><span className={`log-mark ${l.level.toLowerCase()}`}><Activity size={15}/></span><div><strong>{l.message}</strong><span className="mono faint">{[l.botId,l.instanceId,l.jobId].filter(Boolean).join(' / ')||'system'}</span></div><time>{rel(l.at)}</time></article>)}</div></section>}
      <footer className="footer">BBOT CONSOLE <span>{client.mode==='remote'?'LIVE':'MOCK'} · JAVA 1.8.9</span></footer>
    </main>
    <nav className="bottom-nav" aria-label="モバイルナビゲーション">{nav.slice(0,4).map(n=><NavButton key={n.id} {...n} page={page} setPage={go}/>)}<button className={`nav-button ${['accounts','settings','logs'].includes(page)?'selected':''}`} aria-expanded={more} onClick={()=>setMore(true)}><MoreHorizontal size={20}/><span>More</span></button></nav>
    {more&&<div className="overlay" onClick={()=>setMore(false)}><div className="sheet" role="dialog" aria-modal="true" aria-label="その他の画面" onClick={e=>e.stopPropagation()}><div className="sheet-head"><b>More</b><button className="icon-button" aria-label="閉じる" onClick={()=>setMore(false)}><X size={21}/></button></div>{nav.slice(4).map(n=><button className="sheet-item" key={n.id} onClick={()=>go(n.id)}><n.icon size={19}/>{n.label}<ChevronRight size={17}/></button>)}<div className="sheet-foot">{client.mode==='remote'?'REMOTE':'MOCK'} MODE · JAVA EDITION 1.8.9</div></div></div>}
    {accountOpen&&<div className="overlay" onClick={()=>setAccountOpen(false)}><div className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="account-title" onClick={e=>e.stopPropagation()}><div className="sheet-head"><b id="account-title">Add account</b><button className="icon-button" aria-label="閉じる" onClick={()=>setAccountOpen(false)}><X size={21}/></button></div><div className="form-body"><div className="type-tabs" role="group" aria-label="Account方式"><button className={accountKind==='SESSION'?'chosen':''} onClick={()=>setAccountKind('SESSION')}>Session Account</button><button className={accountKind==='MICROSOFT'?'chosen':''} onClick={()=>setAccountKind('MICROSOFT')}>Microsoft</button></div><label className="field-label" htmlFor="account-label">Display label</label><input id="account-label" maxLength={40} value={accountLabel} onChange={e=>setAccountLabel(e.target.value)} placeholder="例: Scout 07" autoComplete="off"/><div className="token-note"><ShieldCheck size={19}/><span>Mockではtoken入力を行いません。秘密情報は保持・保存されません。</span></div><button className="button accent full" onClick={()=>{try{client.addAccount(accountLabel,accountKind);setAccountOpen(false);setAccountLabel('');setToast('Mock Accountを追加しました')}catch(err){setToast(err instanceof Error?err.message:'追加に失敗しました')}}}><Plus size={17}/> Add Mock account</button></div></div></div>}
    {liveBotId&&snapshot.bots.find(bot=>bot.id===liveBotId)&&<LiveViewModal bot={snapshot.bots.find(bot=>bot.id===liveBotId)!} remoteViewer={client.mode==='remote'?snapshot.viewer??null:undefined} onClose={()=>setLiveBotId(null)}/>}
    {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  </div>
}
function Dashboard({data,active,live,pending,go,perform}:{data:Snapshot;active:number;live:number;pending:number;go:(p:Page)=>void;perform:(task:()=>void,success?:string)=>void}){
  const suspect=data.instances.filter(i=>i.status==='SUSPECT').length;
  return <div className="dashboard"><div className="hero-status"><div className="hero-icon"><Activity size={22}/></div><div><div className="eyebrow">FLEET STATUS</div><strong>{active} of {data.bots.length} bots online</strong><p>Java 1.8.9 <span className="bullet">·</span> {client.mode==='remote'?'Live backend':'Mock data'}</p></div><span className="hero-wave" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></span></div>
    <div className="metrics"><div className="metric"><div className="metric-label"><BotIcon size={17}/> BOTS</div><strong>{active}<span> / {data.settings.maxBots}</span></strong><small>{live} in Pit</small></div><div className="metric"><div className="metric-label"><Layers3 size={17}/> INSTANCES</div><strong>{data.instances.length}</strong><small>{suspect?`${suspect} need attention`:'All observed'}</small></div><div className="metric"><div className="metric-label"><ListChecks size={17}/> OPEN JOBS</div><strong>{pending}</strong><small>{data.jobs.filter(j=>j.state==='RUNNING').length} running</small></div></div>
    <div className="dashboard-grid"><section className="panel roster-panel"><SectionHead kicker="LIVE ROSTER" title="Bots" action={<button className="link" onClick={()=>go('bots')}>View all <ArrowRight size={15}/></button>}/><div className="roster-list">{data.bots.slice(0,4).map(b=><BotCard key={b.id} bot={b} compact onAction={perform}/>)}</div><button className="row-link" onClick={()=>go('bots')}><span>Manage all {data.bots.length} bots</span><ChevronRight size={17}/></button></section>
      <div className="dashboard-right"><section className="panel"><SectionHead kicker="NETWORK" title="Instances" action={<button className="link" onClick={()=>go('instances')}>View all <ArrowRight size={15}/></button>}/><div className="overview-instances">{data.instances.slice(0,4).map(i=><div className="instance-line" key={i.id}><span className={`ring ${tone(i.status)}`}><Layers3 size={16}/></span><div><strong className="mono">{i.id}</strong><small>{data.bots.filter(b=>b.instanceId===i.id).length} bots</small></div><Badge status={i.status}/></div>)}</div></section>
        <section className="panel recent-panel"><SectionHead kicker="ACTIVITY" title="Recent events" action={<button className="link" onClick={()=>go('logs')}>Logs <ArrowRight size={15}/></button>}/><div className="recent-list">{data.logs.slice(0,3).map(l=><div className="recent-row" key={l.id}><span className={`tiny-dot ${l.level.toLowerCase()}`}/><div><strong>{l.message}</strong><small>{rel(l.at)}</small></div></div>)}</div></section>
      </div></div>
  </div>
}
function SettingSelect({label,value,options,suffix='',onChange}:{label:string;value:number;options:number[];suffix?:string;onChange:(n:number)=>void}){
  return <div className="setting-row"><strong>{label}</strong><label className="select-wrap"><span className="sr-only">{label}</span><select value={value} onChange={e=>onChange(Number(e.target.value))}>{options.includes(value)?null:<option value={value}>{value}{suffix}</option>}{options.map(n=><option key={n} value={n}>{n}{suffix}</option>)}</select><ChevronDown size={13}/></label></div>
}
export { App };
